# Generated by Django 4.1.3 on 2022-11-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodCourt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "foodcourt_name",
                    models.CharField(
                        default="NULL", max_length=30, verbose_name="Название"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        default="NULL", max_length=30, verbose_name="Название"
                    ),
                ),
                (
                    "restaurant_description",
                    models.TextField(
                        default="NULL", max_length=200, verbose_name="Описание"
                    ),
                ),
                (
                    "restaurant_rating",
                    models.IntegerField(default=0, verbose_name="Оценка"),
                ),
                (
                    "restaurant_address",
                    models.TextField(
                        default="NULL", max_length=100, verbose_name="Адрес ресторана"
                    ),
                ),
                (
                    "restaurant_image",
                    models.ImageField(
                        upload_to="restaurantimages/", verbose_name="Картинка"
                    ),
                ),
                (
                    "restaurant_foodcourt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_app.foodcourt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dish_name",
                    models.CharField(
                        default="NULL", max_length=30, verbose_name="Название"
                    ),
                ),
                (
                    "dish_category",
                    models.CharField(
                        default="NULL", max_length=20, verbose_name="Категория"
                    ),
                ),
                (
                    "dish_description",
                    models.TextField(
                        default="NULL", max_length=200, verbose_name="Описание"
                    ),
                ),
                ("dish_price", models.FloatField(default=0, verbose_name="Цена")),
                (
                    "dish_image",
                    models.ImageField(
                        upload_to="dish_images/", verbose_name="Картинка"
                    ),
                ),
                (
                    "dish_restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_app.restaurant",
                    ),
                ),
            ],
        ),
    ]
