# Generated by Django 4.1.3 on 2022-11-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server_app", "0003_restaurant_restaurant_foodcourt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="restaurant_address",
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="restaurant_foodcourt",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="server_app.foodcourt",
            ),
        ),
    ]
