# Generated by Django 4.1.3 on 2022-11-24 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("server_app", "0004_remove_restaurant_restaurant_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_number",
                    models.IntegerField(default=-1, verbose_name="Номер заказа"),
                ),
                (
                    "order_dish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_app.dish",
                    ),
                ),
                (
                    "order_restautant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server_app.restaurant",
                    ),
                ),
            ],
        ),
    ]
