# Generated by Django 4.1.3 on 2022-11-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server_app", "0005_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_quantity",
            field=models.IntegerField(default=-1, verbose_name="Количество блюд"),
        ),
    ]
